Adding module for creating test reports in ReportPortal
nortal/test-automation pull request #2
Opened 2022-07-13 08:25 UTC by esu-justinas

2022-07-18 21:15 UTC, ricardas-buc requested changes

2022-07-18 21:15 UTC, ricardas-buc commented on .gitattributes
> +*.configuration text
Is this is intentional change?

2022-07-18 21:15 UTC, ricardas-buc commented on test-automation-reportportal/src/main/kotlin/com/nortal/test/report/reportportal/CustomScenarioReporter.kt
> +class CustomScenarioReporter : ScenarioReporter() {
custom does not mean much, should have a better name.

2022-07-18 21:15 UTC, ricardas-buc commented on settings.gradle.kts
> +            library("reportportal-cucumber", "com.epam.reportportal", "agent-java-cucumber6").versionRef("reportportal")
I have seen that both junit5 and allure modules are available. Have you checked what they provide compared to vanilla java lib? see: https://github.com/reportportal/allure-java

2022-07-19 07:08 UTC, esu-justinas commented on .gitattributes
> +*.configuration text
Seems like this was unintentional.

2022-07-19 07:12 UTC, esu-justinas commented on settings.gradle.kts
> +            library("reportportal-cucumber", "com.epam.reportportal", "agent-java-cucumber6").versionRef("reportportal")
Took a look at this module. It seems that it is still in BETA version, without any relevant documentation on how to use it. But I'll try to look into it a little deeper, maybe I'll manage to figure out how to integrate it with our allure reports.

2022-07-19 12:34 UTC, esu-justinas commented
Did some investigation on https://github.com/reportportal/allure-java , but it is pretty difficult navigating it without any documentation. It seems that junit5 module in that repo enables allure annotations, which we don't use anyhow at the moment. As for allure-cucumber-6 module, it is still unclear for me how to use it, or what purpose it plays.

So for now, leaving the vanilla java agent lib of ReportPortal.

2022-08-22 14:14 UTC, ricardas-buc approved these changes

2022-08-22 14:15 UTC, merged